let input_sequence = "CAGCCTATTGCATACAACGTACTTGTGTACTCTCCCCACCCCTGGCAGATAAACATGCATAGATCCTACAATATCTGCAGGGTACGACTGGTGCGCGCCCTGCCACGATGGTCAGTACCCGGGTCTCCCAAGTAACCCGACGAATCGAGGCCTTCATGTCCACAGGTCAAGCCCTTTTCAAAGTTCATCTTAGTCGGATATCGAATCTAACTGTCCATAGGCCACACATAAGTCGGTTGGTGCGGCCAATAATTGAGTTCGCTTAGGATTTTGCGTCAAGTGCGAAACGATGAGGTCTTTCCCAAGTGATCCACCTGCTTATCATATCCTCTATTGCGCCGTTGTTAGATGATCGGGTGACAGTATGAAGATTATCTTGTTGTCCTCGTGGAGATAGGCTATATTTGTCATCGCACATGCGTCTTGCGGGTATTCAGGCATACACACATTGGGGATCGTGAGCGTTTCTCCCTGTATCCCTAACAAAACGAACAGATCAAGAACAGTTGCTCCTTTAAGATCCGTTGCCCGACTCGCGGGTTAAGTCAACAGGGAGTATTCCCCCCCCTAGAACGTAAGTGGGTCGAGACGCTTTGCCACATGGCACCCTGTTGATTACAATATACTAGCCTTAGTAACTCGAGAAAAAGTACGCAGATAGTACTTCCACGGATTGCATGCGTAGCGCTCTGGCTTACGTTGTTTCCCAACCTGTGCCTATGACGGTTTGTGCCATCTAATAACAGCACCGCTGCGCGTCCGCCAGGGTGGAGGTGGTTGTGCCTGAGCGCTGACGCGATCTCCACCCGAATCCAACCTTTTTAACATGCGCTTCTCGCTTACAGCAACGATCCATTACCACTAGCTGCTCATGGGGGACAGCCTTATAACCTTCTTCATACTGGAGCATTAAGCATGGGAGACCGCTTATAATACAACTTCCGCAAAGTTGGGTGGCGAGATGGTGATCTGGGTCCCGACG"


let translate (nucleotide: char) = 
    // Translate T into U, otherwise just return the character

    match nucleotide with
        | 'T' -> 'U'
        | _ -> nucleotide
        
        
let output_sequence = input_sequence
                        |> List.ofSeq
                        |> List.map translate
                        |> Array.ofList
                        |> System.String.Concat

        
printfn "%s" output_sequence
